# Generated by Django 3.2.6 on 2021-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=255)),
                ('month_of_release', models.CharField(max_length=255)),
                ('passenger_type', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('visa', models.CharField(max_length=255)),
                ('country_of_residence', models.CharField(max_length=255)),
                ('estimate', models.CharField(max_length=255)),
                ('standard_error', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
